add_newline = false

format = """
$directory$git_branch$git_status$conda$character
"""

[directory]
truncation_length = 3
truncate_to_repo = false
format = " "

[conda]
ignore_base = true
format = " "

[gcloud]
disabled = true

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
