format = """
$directory\
$git_branch\
$git_status\
$python\
$nodejs\
$cmd_duration\
$line_break\
$character"""

add_newline = true

[character]
success_symbol = "[>](bold green)"
error_symbol = "[>](bold red)"
vimcmd_symbol = "[<](bold yellow)"

[directory]
style = "bold blue"
truncation_length = 3
truncate_to_repo = false

[git_branch]
format = " [$symbol$branch]($style)"
style = "bold purple"
symbol = "git:"

[git_status]
format = " [$all_status$ahead_behind]($style)"
style = "bold yellow"

[cmd_duration]
format = " [$duration]($style)"
style = "dimmed white"
min_time = 1000

[python]
format = " [py $version]($style)"
style = "green"

[nodejs]
format = " [node $version]($style)"
style = "green"
